on:
  pull_request:
  push:
    branches:
      - main
      - beta
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v15
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix flake check --show-trace
  # release:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.repository_owner == 'mirkolenz' && github.event_name == 'push' }}
  #   needs: [check]
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: docker/setup-qemu-action@v3
  #       with:
  #         platforms: arm64
  #     - uses: DeterminateSystems/nix-installer-action@v14
  #       with:
  #         extra-conf: |
  #           extra-platforms = aarch64-linux
  #     - uses: DeterminateSystems/magic-nix-cache-action@v8
  #     - run: nix run .#docker-manifest --impure
  #       env:
  #         GH_TOKEN: ${{ github.token }}
